const Menu =[
    {
        id: 1,
        Image: "Images/maggi.jpg",
        name: 'Maggi',
        category: 'lunch',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },
    {
        id: 2,
        Image: "Images/allupakoida.jpg",
        name: 'Allu Pakodra',
        category: 'evening',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },
    {
        id: 3,
        Image: "Images/corn.jpg",
        name: 'Corn',
        category: 'breakfast',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },
    {
        id: 4,
        Image: "Images/chola.jpg",
        name: 'Chola',
        category: 'lunch',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },{
        id: 5,
        Image: "Images/momo.jpg",
        name: 'Momo',
        category: 'dinner',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },{
        id: 6,
        Image: "Images/pizza.jpg",
        name: 'Pizza',
        category: 'dinner',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },{
        id: 7,
        Image: "Images/puri.jpg",
        name: 'Purii',
        category: 'breakfast',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },{
        id: 8,
        Image: "Images/rajmarice.jpg",
        name: 'Rajma Chawal',
        category: 'evening',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },{
        id: 9,
        Image: "Images/samosa.jpg",
        name: 'Samosa',
        category: 'evening',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },
    {
        id: 10,
        Image: "Images/rotiwithmeat.jpg",
        name: 'Roti With Meat',
        category: 'dinner',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
    },
    {
        id: 11,
        Image: "Images/sweet.jpg",
        name: 'Sweet',
        category: 'dinner',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
 
    },
    { id: 12,
        Image: "Images/vegthali.jpg",
        name: 'Veg Thali',
        category: 'lunch',
        price: 100,
        description:' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque sunt dolorem repudiandae vitae voluptate voluptas, hic quas minus non provident quis animi a nam optio minima ut sint dignissimos sapiente.',
 }
]

export default Menu;